// Browser mock backend: serves presets generated by the real Rust engine
// (`pnpm gen:mock`) behind the same TokenstreakApi interface as Tauri IPC.
//
// URL parameters (read by src/api/index.ts):
//   ?preset=<id>   new-user | first-run-reveal | streak-30 | heavy-multi-tool | goal-hit | streak-at-risk
//   ?live=1        stream synthetic tokens into today (default on for goal-hit)
//   ?speed=<n>     live-tick speed multiplier (default 1)

import type { ApiEvents, SettingsPatch, TokenstreakApi, Unsubscribe } from "../client";
import type {
  Achievement,
  AppInfo,
  AppSnapshot,
  Breakdown,
  DayRow,
  GoalsInput,
  MockPreset,
  PriceRefreshResult,
  RangeQuery,
  Settings,
  ShareCardData,
  ShareOptions,
  Tool,
} from "../types";
import { evaluate, setGoal, totalsOf, weekStart } from "./streaks";

export { PRESET_IDS, type PresetId } from "./presetIds";

const loaders = import.meta.glob<MockPreset>("./presets/*.json", { import: "default" });

export async function loadPreset(id: string): Promise<MockPreset> {
  const load = loaders[`./presets/${id}.json`] ?? loaders["./presets/streak-30.json"];
  if (!load) throw new Error(`unknown mock preset ${id}`);
  return structuredClone(await load());
}

export interface MockOptions {
  preset: string;
  live?: boolean;
  speed?: number;
}

type Listener = (payload: unknown) => void;

const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

function deepMerge<T>(base: T, patch: unknown): T {
  if (patch === null || typeof patch !== "object" || Array.isArray(patch)) return patch as T;
  const out: Record<string, unknown> = { ...(base as Record<string, unknown>) };
  for (const [k, v] of Object.entries(patch as Record<string, unknown>)) {
    out[k] = v !== null && typeof v === "object" && !Array.isArray(v) ? deepMerge(out[k], v) : v;
  }
  return out as T;
}

export async function createMockApi(opts: MockOptions): Promise<TokenstreakApi> {
  const preset = await loadPreset(opts.preset);
  let snap: AppSnapshot = preset.snapshot;
  // Presets are generated from a temp folder; show the paths a real Mac would have.
  const HOME: Record<string, string> = { claude: "/Users/you/.claude/projects", codex: "/Users/you/.codex/sessions", gemini: "/Users/you/.gemini/tmp" };
  snap.sources = snap.sources.map((s) => ({ ...s, paths: s.paths.map((p) => (p.includes("tokenstreak-mock-work") ? HOME[s.tool] ?? p : p)) }));
  let settings: Settings = preset.settings;
  const listeners = new Map<keyof ApiEvents, Set<Listener>>();
  const emit = <E extends keyof ApiEvents>(e: E, payload: ApiEvents[E]) =>
    listeners.get(e)?.forEach((l) => l(payload));

  const today = () => snap.today.date;

  /** Re-derives goals, streaks and per-day goal flags after a change. */
  function recompute(): void {
    const history = snap.goals.history.length
      ? snap.goals.history
      : [{ effectiveFrom: snap.days[0]?.date ?? today(), daily: snap.goals.daily, weekly: snap.goals.weekly }];
    const r = evaluate(totalsOf(snap.days), history, today(), settings.restDays, settings.weekStartsOn);
    const byDate = new Map(r.days.map((d) => [d.date, d]));
    snap.days = snap.days.map((d) => {
      const e = byDate.get(d.date);
      return e ? { ...d, goal: e.goal, met: e.met, streak: e.streak } : d;
    });
    const g = history[history.length - 1]!;
    const t = snap.today.tokens.total;
    snap.today = { ...snap.today, goal: g.daily, progress: g.daily ? t / g.daily : 0, met: g.daily > 0 && t >= g.daily, remaining: Math.max(0, g.daily - t) };
    const ws = weekStart(today(), settings.weekStartsOn);
    const weekTokens = snap.days.filter((d) => d.date >= ws && d.date <= today()).reduce((a, d) => a + d.total, 0);
    snap.goals = {
      ...snap.goals,
      daily: g.daily,
      weekly: g.weekly,
      weekStartsOn: settings.weekStartsOn,
      thisWeek: {
        ...snap.goals.thisWeek,
        tokens: weekTokens,
        goal: g.weekly,
        progress: g.weekly ? weekTokens / g.weekly : 0,
        met: g.weekly > 0 && weekTokens >= g.weekly,
      },
    };
    snap.streak = {
      ...snap.streak,
      current: r.current,
      longest: r.longest,
      longestStart: r.longestStart,
      longestEnd: r.longestEnd,
      currentStart: r.currentStart,
      todayMet: r.todayMet,
      atRisk: !r.todayMet && r.current > 0,
      weeklyCurrent: r.weeklyCurrent,
      weeklyLongest: r.weeklyLongest,
      restDays: settings.restDays,
    };
  }

  function publish(): AppSnapshot {
    snap = { ...snap, generatedAt: new Date().toISOString() };
    emit("snapshot", structuredClone(snap));
    return structuredClone(snap);
  }

  function applyGoals(g: GoalsInput): void {
    const weekly = g.weekly > 0 ? g.weekly : g.daily * 5;
    snap.goals.history = setGoal(snap.goals.history, today(), g.daily, weekly);
    settings = { ...settings, dailyGoal: g.daily, weeklyGoal: weekly };
    recompute();
  }

  /** Adds tokens to today, as if an agent were working right now. */
  function addTokens(amount: number): void {
    const before = snap.today.met;
    const tools: Tool[] = ["claude", "codex", "gemini"];
    const weights = snap.today.byTool.map((t) => t.tokens + 1);
    const wsum = weights.reduce((a, b) => a + b, 0);
    const hour = new Date(snap.generatedAt).getHours();
    const byTool = snap.today.byTool.map((t, i) => {
      const add = Math.round((amount * (weights[i] ?? 0)) / wsum);
      return { ...t, tokens: t.tokens + add, cost: t.cost + add * 2.5e-6 };
    });
    const total = byTool.reduce((a, t) => a + t.tokens, 0);
    const added = total - snap.today.tokens.total;
    const tokens = { ...snap.today.tokens, cacheRead: snap.today.tokens.cacheRead + Math.round(added * 0.85), input: snap.today.tokens.input + Math.round(added * 0.03), output: snap.today.tokens.output + Math.round(added * 0.04), cacheWrite: snap.today.tokens.cacheWrite + (added - Math.round(added * 0.85) - Math.round(added * 0.03) - Math.round(added * 0.04)), total };
    const hourly = [...snap.today.hourly];
    hourly[hour] = (hourly[hour] ?? 0) + added;
    snap.today = {
      ...snap.today,
      tokens,
      cost: snap.today.cost + added * 2.5e-6,
      byTool: byTool.map((t) => ({ ...t, share: total ? t.tokens / total : 0 })),
      hourly,
      messages: snap.today.messages + 1,
      lastActivityAt: new Date().toISOString(),
    };
    const idx = snap.days.findIndex((d) => d.date === today());
    if (idx >= 0) {
      const d = snap.days[idx]!;
      const next: DayRow = { ...d, total, cost: snap.today.cost, messages: d.messages + 1 };
      for (const t of tools) next[t] = byTool.find((b) => b.tool === t)?.tokens ?? next[t];
      snap.days[idx] = next;
    }
    snap.lifetime = { ...snap.lifetime, tokens: { ...snap.lifetime.tokens, total: snap.lifetime.tokens.total + added } };
    recompute();
    if (!before && snap.today.met && snap.onboarding.completed) {
      const celebration = {
        date: today(),
        tokens: snap.today.tokens.total,
        goal: snap.today.goal,
        streak: snap.streak.current,
        newRecord: snap.streak.current >= snap.streak.longest && snap.streak.current > 1,
      };
      snap.celebration = celebration;
      publish();
      emit("goal-reached", celebration);
      return;
    }
    publish();
  }

  const live = opts.live ?? opts.preset === "goal-hit";
  if (live) {
    const speed = Math.max(0.1, opts.speed ?? 1);
    const step = Math.max(1, Math.round(snap.today.goal * 0.012));
    setInterval(() => addTokens(step), 1500 / speed);
  }

  const breakdownFor = (range: RangeQuery): Breakdown => {
    const direct = preset.breakdowns[range.kind];
    if (direct && range.kind !== "custom") return structuredClone(direct);
    const all = structuredClone(preset.breakdowns["all"]!);
    const from = range.from ?? all.from;
    const to = range.to ?? all.to;
    all.series = all.series.filter((d) => d.date >= from && d.date <= to);
    return { ...all, from, to };
  };

  const api: TokenstreakApi = {
    backend: "mock",
    async getSnapshot() {
      return structuredClone(snap);
    },
    async getBreakdown(range) {
      await sleep(40);
      return breakdownFor(range);
    },
    async getSettings() {
      return structuredClone(settings);
    },
    async updateSettings(patch: SettingsPatch) {
      const prev = settings;
      settings = deepMerge(settings, patch);
      if (settings.dailyGoal !== prev.dailyGoal || settings.weeklyGoal !== prev.weeklyGoal) {
        applyGoals({ daily: settings.dailyGoal, weekly: settings.weeklyGoal });
      } else {
        recompute();
      }
      publish();
      emit("settings", structuredClone(settings));
      return structuredClone(settings);
    },
    async setGoals(goals) {
      applyGoals(goals);
      emit("settings", structuredClone(settings));
      return publish();
    },
    async completeOnboarding(goals) {
      applyGoals(goals);
      snap.onboarding = { ...snap.onboarding, completed: true };
      snap.achievements = snap.achievements.map((a) => ({ ...a, isNew: false }));
      return publish();
    },
    async refresh() {
      await sleep(450);
      snap.status = { ...snap.status, lastScanAt: new Date().toISOString() };
      return publish();
    },
    async refreshPrices(): Promise<PriceRefreshResult> {
      await sleep(900);
      snap.pricing = { ...snap.pricing, updatedAt: new Date().toISOString() };
      publish();
      return { ok: true, pricing: snap.pricing, error: null };
    },
    async getShareCard(options: ShareOptions): Promise<ShareCardData> {
      const card = structuredClone(preset.shareCards[options.format] ?? preset.shareCards["square"]!);
      const allow = options.includeProjectNames ?? settings.share.showProjectNames;
      if (!allow) card.topProjects = null;
      else card.topProjects = preset.breakdowns["last30"]?.byProject.slice(0, 3).map((p) => p.label) ?? [];
      card.cost = settings.share.showCost ? (preset.breakdowns["last30"]?.cost ?? null) : null;
      card.streak = snap.streak.current;
      return card;
    },
    async exportCsv(range) {
      const b = breakdownFor(range);
      const rows = b.series.map((d) => [d.date, d.total, d.claude, d.codex, d.gemini, d.cost.toFixed(4), d.goal, d.met, d.streak].join(","));
      return ["date,total_tokens,claude,codex,gemini,cost_usd_estimate,goal,goal_met,streak", ...rows].join("\n") + "\n";
    },
    async saveExport(fileName, dataBase64) {
      const a = document.createElement("a");
      a.href = `data:application/octet-stream;base64,${dataBase64}`;
      a.download = fileName;
      a.click();
      return `~/Downloads/${fileName}`;
    },
    async acknowledgeCelebration(date) {
      if (snap.celebration?.date === date) snap.celebration = null;
      publish();
    },
    async acknowledgeAchievements(ids) {
      snap.achievements = snap.achievements.map((a: Achievement) => (ids.includes(a.id) ? { ...a, isNew: false } : a));
      publish();
    },
    async getAppInfo(): Promise<AppInfo> {
      return { version: "0.1.0-mock", dataDir: "~/Library/Application Support/app.tokenstreak.desktop", backend: "mock", launchAtLogin: settings.launchAtLogin, notificationsPermitted: null };
    },
    async openDashboard() {
      const u = new URL(window.location.href);
      u.searchParams.set("view", "dashboard");
      window.location.href = u.toString();
    },
    async hidePopover() {},
    async setPopoverHeight() {},
    async quit() {},
    async openExternal(url) {
      window.open(url, "_blank", "noopener");
    },
    async locateTool(tool) {
      await sleep(300);
      settings = deepMerge(settings, { tools: { [tool]: { enabled: true, customPaths: [`/Users/you/logs/${tool}`] } } });
      emit("settings", structuredClone(settings));
      return structuredClone(settings);
    },
    async openSettings() {
      const u = new URL(window.location.href);
      u.searchParams.set("view", "dashboard");
      u.searchParams.set("section", "settings");
      window.location.href = u.toString();
    },
    async revealLogs() {},
    on<E extends keyof ApiEvents>(event: E, cb: (payload: ApiEvents[E]) => void): Unsubscribe {
      const set = listeners.get(event) ?? new Set<Listener>();
      set.add(cb as Listener);
      listeners.set(event, set);
      return () => set.delete(cb as Listener);
    },
  };
  // Expose controls for Playwright / the launch-video agent.
  (window as unknown as { __tokenstreakMock?: unknown }).__tokenstreakMock = {
    preset: preset.id,
    addTokens,
    triggerGoalReached: () => addTokens(Math.max(1, snap.today.remaining + 1)),
    emit,
    snapshot: () => structuredClone(snap),
  };
  return api;
}
